// vue-analytics/src/components/ExportMenu.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from "vue";
import type { ExportFormat, ExportJobDto } from "@surveycraft/shared-types";
import { useExportJobs } from "../composables/useExportJobs";

const props = defineProps<{
  apiBaseUrl: string;
  formId: string;
}>();

const { jobs, isCreating, createExport, downloadExport } = useExportJobs(props.apiBaseUrl, props.formId);

const isOpen = ref(false);
const menuRef = ref<HTMLElement | null>(null);
const createError = ref(false);

const FORMAT_LABELS: Record<ExportFormat, string> = { CSV: "CSV", EXCEL: "Excel", PDF: "PDF" };
const STATUS_META: Record<ExportJobDto["status"], { label: string; className: string }> = {
  PENDING: { label: "У черзі", className: "status-pending" },
  PROCESSING: { label: "Генерується...", className: "status-processing" },
  COMPLETED: { label: "Готово", className: "status-completed" },
  FAILED: { label: "Помилка", className: "status-failed" },
};

const recentJobs = computed(() => jobs.value.slice(0, 5));

const handleCreate = async (format: ExportFormat) => {
  createError.value = false;
  try {
    await createExport(format);
  } catch {
    createError.value = true;
  }
};

const handleClickOutside = (event: MouseEvent) => {
  if (menuRef.value && !menuRef.value.contains(event.target as Node)) {
    isOpen.value = false;
  }
};

onMounted(() => document.addEventListener("mousedown", handleClickOutside));
onUnmounted(() => document.removeEventListener("mousedown", handleClickOutside));
</script>

<template>
  <div ref="menuRef" class="export-menu">
    <button type="button" class="trigger" @click="isOpen = !isOpen">
      <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3"
        />
      </svg>
      Експорт
    </button>

    <div v-if="isOpen" class="dropdown">
      <p class="section-label">Новий експорт</p>
      <div class="format-grid">
        <button
          v-for="format in (Object.keys(FORMAT_LABELS) as ExportFormat[])"
          :key="format"
          type="button"
          :disabled="isCreating"
          class="format-btn"
          @click="handleCreate(format)"
        >
          {{ FORMAT_LABELS[format] }}
        </button>
      </div>

      <p v-if="createError" class="error-text">Не вдалося поставити завдання в чергу. Спробуйте ще раз.</p>

      <hr class="divider" />

      <p class="section-label">Історія</p>

      <p v-if="recentJobs.length === 0" class="empty-text">Ще не було жодного експорту</p>
      <div v-else class="history-list">
        <div v-for="job in recentJobs" :key="job.id" class="history-row">
          <div class="history-info">
            <div v-if="job.status === 'PENDING' || job.status === 'PROCESSING'" class="spinner" />
            <svg
              v-else-if="job.status === 'COMPLETED'"
              aria-hidden="true"
              class="status-icon status-completed"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2.5"
            >
              <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 12.75l6 6 9-13.5" />
            </svg>
            <svg
              v-else
              aria-hidden="true"
              class="status-icon status-failed"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2.5"
            >
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>

            <div class="history-text">
              <p class="history-format">{{ FORMAT_LABELS[job.format] }}</p>
              <p class="history-status" :class="STATUS_META[job.status].className">
                {{ job.status === "FAILED" && job.error ? job.error : STATUS_META[job.status].label }}
              </p>
            </div>
          </div>

          <button
            v-if="job.status === 'COMPLETED'"
            type="button"
            class="download-btn"
            aria-label="Завантажити"
            title="Завантажити"
            @click="downloadExport(job)"
          >
            <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3"
              />
            </svg>
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.export-menu {
  position: relative;
}
.trigger {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  border-radius: 8px;
  border: 1px solid #e2e8f0;
  padding: 6px 12px;
  font-size: 12px;
  font-weight: 700;
  color: #334155;
  background: white;
  cursor: pointer;
}
.trigger:hover {
  background: #f8fafc;
}
.trigger svg {
  height: 16px;
  width: 16px;
}
.dropdown {
  position: absolute;
  right: 0;
  margin-top: 6px;
  width: 288px;
  border-radius: 12px;
  border: 1px solid #e2e8f0;
  background: white;
  padding: 12px;
  box-shadow: 0 10px 25px rgba(15, 23, 42, 0.1);
  z-index: 30;
}
.section-label {
  padding: 0 4px;
  font-size: 11px;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  color: #94a3b8;
  margin: 0;
}
.format-grid {
  margin-top: 8px;
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 6px;
}
.format-btn {
  border-radius: 8px;
  border: 1px solid #e2e8f0;
  background: #f8fafc;
  padding: 8px 0;
  font-size: 12px;
  font-weight: 700;
  color: #334155;
  cursor: pointer;
}
.format-btn:hover:not(:disabled) {
  background: #eef2ff;
  border-color: #c7d2fe;
  color: #4f46e5;
}
.format-btn:disabled {
  opacity: 0.5;
  cursor: default;
}
.error-text {
  margin-top: 8px;
  font-size: 11px;
  font-weight: 500;
  color: #dc2626;
}
.divider {
  margin: 12px 0;
  border: none;
  border-top: 1px solid #f1f5f9;
}
.empty-text {
  padding: 12px 4px;
  font-size: 12px;
  color: #94a3b8;
}
.history-list {
  margin-top: 6px;
  display: flex;
  flex-direction: column;
  gap: 4px;
}
.history-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
  border-radius: 8px;
  padding: 6px;
}
.history-row:hover {
  background: #f8fafc;
}
.history-info {
  display: flex;
  align-items: center;
  gap: 8px;
  min-width: 0;
}
.spinner {
  height: 14px;
  width: 14px;
  flex-shrink: 0;
  border-radius: 999px;
  border: 2px solid #e2e8f0;
  border-top-color: #6366f1;
  animation: spin 0.6s linear infinite;
}
@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}
.status-icon {
  height: 14px;
  width: 14px;
  flex-shrink: 0;
}
.status-completed {
  color: #059669;
}
.status-failed {
  color: #dc2626;
}
.status-pending {
  color: #94a3b8;
}
.status-processing {
  color: #d97706;
}
.history-text {
  min-width: 0;
}
.history-format {
  font-size: 12px;
  font-weight: 700;
  color: #334155;
  margin: 0;
}
.history-status {
  font-size: 10px;
  font-weight: 500;
  margin: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.download-btn {
  flex-shrink: 0;
  border-radius: 8px;
  padding: 6px;
  border: none;
  background: transparent;
  color: #94a3b8;
  cursor: pointer;
}
.download-btn:hover {
  background: #eef2ff;
  color: #4f46e5;
}
.download-btn svg {
  height: 16px;
  width: 16px;
}
</style>

// react-frontend/src/pages/analytics/components/ExportMenu.tsx
import { useEffect, useRef, useState } from "react";
import {
  useCreateExportMutation,
  useDownloadExportMutation,
  useExportJobsQuery,
} from "../hooks/useExport";
import { type ExportFormat, type ExportJobDto } from "../../../types/export";

const FORMAT_LABELS: Record<ExportFormat, string> = {
  CSV: "CSV",
  EXCEL: "Excel",
  PDF: "PDF",
};

const STATUS_META: Record<ExportJobDto["status"], { label: string; className: string }> = {
  PENDING: { label: "У черзі", className: "text-slate-400" },
  PROCESSING: { label: "Генерується...", className: "text-amber-500" },
  COMPLETED: { label: "Готово", className: "text-emerald-600" },
  FAILED: { label: "Помилка", className: "text-rose-600" },
};

function StatusIcon({ status }: { status: ExportJobDto["status"] }) {
  if (status === "PENDING" || status === "PROCESSING") {
    return (
      <div className="h-3.5 w-3.5 shrink-0 animate-spin rounded-full border-2 border-slate-200 border-t-indigo-500" />
    );
  }

  if (status === "COMPLETED") {
    return (
      <svg
        className="h-3.5 w-3.5 shrink-0 text-emerald-600"
        fill="none"
        viewBox="0 0 24 24"
        strokeWidth="2.5"
        stroke="currentColor"
      >
        <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
      </svg>
    );
  }

  return (
    <svg
      className="h-3.5 w-3.5 shrink-0 text-rose-600"
      fill="none"
      viewBox="0 0 24 24"
      strokeWidth="2.5"
      stroke="currentColor"
    >
      <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
    </svg>
  );
}

export default function ExportMenu({ formId }: { formId: string }) {
  const [isOpen, setIsOpen] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);

  const { data: jobs = [] } = useExportJobsQuery(formId);
  const createExport = useCreateExportMutation(formId);
  const downloadExport = useDownloadExportMutation(formId);

  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (menuRef.current && !menuRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  const recentJobs = jobs.slice(0, 5);

  return (
    <div className="relative" ref={menuRef}>
      <button
        onClick={() => setIsOpen((v) => !v)}
        className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-bold text-slate-700 hover:bg-slate-50 transition-colors cursor-pointer"
      >
        <svg
          className="h-4 w-4"
          fill="none"
          viewBox="0 0 24 24"
          strokeWidth="2"
          stroke="currentColor"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3"
          />
        </svg>
        Експорт
      </button>

      {isOpen && (
        <div className="absolute right-0 mt-1.5 w-72 origin-top-right rounded-xl border border-slate-200 bg-white p-3 shadow-lg ring-1 ring-black/5 z-30 animate-in fade-in slide-in-from-top-1 duration-100">
          <p className="px-1 text-[11px] font-bold uppercase tracking-wider text-slate-400">
            Новий експорт
          </p>
          <div className="mt-2 grid grid-cols-3 gap-1.5">
            {(Object.keys(FORMAT_LABELS) as ExportFormat[]).map((format) => (
              <button
                key={format}
                onClick={() => createExport.mutate(format)}
                disabled={createExport.isPending}
                className="rounded-lg border border-slate-200 bg-slate-50 py-2 text-xs font-bold text-slate-700 hover:bg-indigo-50 hover:border-indigo-200 hover:text-indigo-600 disabled:opacity-50 transition-colors cursor-pointer"
              >
                {FORMAT_LABELS[format]}
              </button>
            ))}
          </div>

          {createExport.isError && (
            <p className="mt-2 text-[11px] font-medium text-rose-600">
              Не вдалося поставити завдання в чергу. Спробуйте ще раз.
            </p>
          )}

          <hr className="my-3 border-slate-100" />

          <p className="px-1 text-[11px] font-bold uppercase tracking-wider text-slate-400">
            Історія
          </p>

          {recentJobs.length === 0 ? (
            <p className="px-1 py-3 text-xs text-slate-400">Ще не було жодного експорту</p>
          ) : (
            <div className="mt-1.5 flex flex-col gap-1">
              {recentJobs.map((job) => {
                const meta = STATUS_META[job.status];
                return (
                  <div
                    key={job.id}
                    className="flex items-center justify-between gap-2 rounded-lg px-1.5 py-1.5 hover:bg-slate-50"
                  >
                    <div className="flex items-center gap-2 min-w-0">
                      <StatusIcon status={job.status} />
                      <div className="min-w-0">
                        <p className="text-xs font-bold text-slate-700">
                          {FORMAT_LABELS[job.format]}
                        </p>
                        <p className={`text-[10px] font-medium truncate ${meta.className}`}>
                          {job.status === "FAILED" && job.error ? job.error : meta.label}
                        </p>
                      </div>
                    </div>

                    {job.status === "COMPLETED" && (
                      <button
                        onClick={() => downloadExport.mutate(job)}
                        title="Завантажити"
                        className="shrink-0 rounded-lg p-1.5 text-slate-400 hover:bg-indigo-50 hover:text-indigo-600 transition-colors cursor-pointer"
                      >
                        <svg
                          className="h-4 w-4"
                          fill="none"
                          viewBox="0 0 24 24"
                          strokeWidth="2"
                          stroke="currentColor"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3"
                          />
                        </svg>
                      </button>
                    )}
                  </div>
                );
              })}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
